application:
  client:
    tmdb:
      token: TokenTmdb
  ernestotech:
    azure:
      key-vault:
        endpoint: https://kvernestointech.vault.azure.net/
        clientId: ${AZURE_APP_CLIENT_ID}
        clientSecret: ${AZURE_APP_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        secrets:
          tbdbTokenSecret: secTmdb